### ISSUE TITLE
Add link to BA homepage

### ISSUE THREAD

**Issue by sjtrny** [forecastlab/forecast_dash#106]
> The about-page mentions the discipline. It would be good to put a link to our discipline page there https://www.sydney.edu.au/business/our-research/research-areas/business-analytics.html

**Comment by sjtrny** [comment]
Put USYD logo in the nav/header bar.

**Comment by ardimirzaei** [comment]
Logo is in the header, but had to update from simple navbar to customizable navbar. That being said, need to callback that can handle the collapsible navbar:

```
@self.callback(
Output("navbar-collapse", "is_open"),
[Input("navbar-toggler", "n_clicks")],
[State("navbar-collapse", "is_open")],
)
def toggle_navbar_collapse(n, is_open):
    if n:
        return not is_open
    return is_open
```
