### ISSUE TITLE
Add metadata to downloadable spreadsheet

### ISSUE THREAD

**Issue by sjtrny** [forecastlab/forecast_dash#110]
Metadata should include:
- date of forecast
- period of data used
- where forecast came from (link back to forecast lab)

**Comment by ardimirzaei** [comment]
That last commit produces a sheet in the download data as follows:

![image](https://user-images.githubusercontent.com/45409241/174919494-d1e6d46e-299e-481c-ae0f-f68fe27609f3.png)

However, the period frequency information should be added into the pickle. Can be updated when working on the model versioning (#131)
