### ISSUE TITLE
Fix cv table layout when large numbers present

### ISSUE THREAD

**Issue by sjtrny** [forecastlab/forecast_dash#113]
![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/3364754/146714146-3c34b7d9-66fb-49cc-a087-11deb172ad7c.png)

**Comment by ardimirzaei** [comment]
What about a mix of Scientific and decimal places :


![image](https://user-images.githubusercontent.com/45409241/171986703-0f11abe3-04df-4fb9-90d7-5a18b996d52b.png)
