### ISSUE TITLE
Display error when git info not available

### ISSUE THREAD

**Issue by sjtrny** [forecastlab/forecast_dash#132]
https://github.com/forecastlab/forecast_dash/pull/130/files/beb8db05224b50a4524ad0676c35cd7742356896#r891106109

**Comment by ardimirzaei** [comment]
This is what we have so far: 
![image](https://user-images.githubusercontent.com/45409241/180115398-3deb677a-c807-4045-b29c-6bffff5912dc.png)

If that is fine, maybe we close this issue.
