### ISSUE TITLE
Australia unemployment/underemployment

### ISSUE THREAD

**Issue by sjtrny** [forecastlab/forecast_dash#140]
These series are no longer available from ausmacrodata. Investigate direct ABS integration to restore these series.

**Comment by ardimirzaei** [comment]
I'm not able to find granular data from the ABS api. Or I'm not looking at the right codes. ABS does have another resource called DataLab which has microdata. But I think this is a paid service. [https://www.abs.gov.au/statistics/microdata-tablebuilder/datalab](https://www.abs.gov.au/statistics/microdata-tablebuilder/datalab)

**Comment by Andywang201605** [comment]
https://www.abs.gov.au/articles/historical-charts-august-1966-april-2022 this page contains historical unemployment rate - but I don't think it is a realiable & stable place to get the data
