### ISSUE TITLE
Parallelise data download and running models 

### ISSUE THREAD

**Issue by sjtrny** [forecastlab/forecast_dash#31]
As title

**Comment by david-houseman** [comment]
+1. Models generation with the UK patch now taking over 20 mins on my machine. Download is still acceptably quick.

Another time-saving idea is for the forecasts pickle to cache a checksum (or hashsum) of the downloaded pickle. That way, if the downloaded pickle doesn't change, the checksums will match and the forecasts can be safely re-used without recomputing.

**Comment by sjtrny** [comment]
Closed by https://github.com/forecastlab/forecast_dash/pull/47
