### ISSUE TITLE
Create discourse for discussion/support

### ISSUE THREAD

**Issue by sjtrny** [forecastlab/forecast_dash#54]

**Comment by david-houseman** [comment]
Hi Stephen, I have created a new branch `contact_form` with a "Contact" page with a form for users to fill out name/email/subject/message as a kind of feedback mechanism for the app. Is this the kind of thing you had in mind? Thanks, David

![contact_form](https://user-images.githubusercontent.com/67889178/96420040-b4797e00-1240-11eb-9f3f-054058e60360.png)

**Comment by david-houseman** [comment]
This approach needs access to the ISP's SMTP server. Could also consider setting up a webmaster@business-forecast-lab.com email account to receive the generated mail.

**Comment by sjtrny** [comment]
> Is this roughly what you had in mind?

No the issue was for creating a forum using https://discourse.org if we ever get a user base large enough to warrant it. But it's not an immediate concern.

The contact page is a good idea though. I'll create a new issue for this.
