### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by david-houseman** [forecastlab/forecast_dash#59]
Just a thought -- will the server adequately handle say 50 concurrent users?

The script attached below uses N concurrent instances of `wget` to simulate N users. The wall-clock time elapsed, in seconds, for N = 1 2 4 8 16 64 128 instances to all complete, are:

[Local web instance] 
http://0.0.0.0:5000/search
1: 0.013
2: 1.015
4: 2.029
8: 2.041
16: 2.065
32: 2.099
64: 2.226
128: 2.301

[Production server]
https://business-forecast-lab.com/search/
1: 3.510
2: 3.527
4: 3.553
8: 10.621
16: 18.999
32: 32.481
64: 32.732
128: Some jobs fail

The results show:
- Locally on my own desktop, 50 concurrent instances are easily served, with elapsed time not varying significantly with N. 
- For the production server, 50 concurrent instances are served successfully, but takes over 30s to complete all instances. This might be a bit on the laggy side for user experience?

Caveats: 
- I am not sure that these results accurately reflect N requests from N different IP addresses: these data reflect N requests all from the same IP address.

Script used to generate these results:

```
#!/bin/bash                                                                                    

## Very simplistic stress testing of the server.                                               
## Thank you to github/cirocosta/stress-test.sh                                                

remote=https://business-forecast-lab.com/search/
local=http://0.0.0.0:5000/search

trap "kill 0" INT

stress() {
    url="$1"
    reps="$2"

    for j in $( seq "$reps" )
    do
        wget -pq --delete-after -O /dev/null "$url" & pidlist="$pidlist $!"
    done

    for job in $pidlist; do
        wait $job || echo "Failed: $job"
    done
}

TIMEFORMAT='%3R'

for url in "$local" "$remote"
do
   echo "$url"
   for reps in 1 2 4 8 16 32 64 128
   do
       echo -n "$reps: "
       time stress "$url" "$reps"
   done
done

```

**Comment by sjtrny** [comment]
Does that wget command execute javascript on the page? I don't have wget installed (and it's taking forever to compile via homebew) to test it. But I have curl and I assume that it would be the same. It just returns the initial react.js layout which I've put below. This means that none of the callbacks are actually used yet - so the problem might actually be worse than what you're seeing here.

Although maybe that script isn't entirely accurate? I tried an equivalent script using curl and it runs in a few seconds for 128 requests on the live website. This is where I got my script from https://gist.github.com/cirocosta/de576304f1432fad5b3a

```
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta charset="UTF-8">
        <title>Find a Series</title>
        <link rel="icon" type="image/x-icon" href="/search/assets/favicon.ico?m=1566116225.1097867">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    </head>
    <body>
        
<div id="react-entry-point">
    <div class="_dash-loading">
        Loading...
    </div>
</div>

        <footer>
            <script id="_dash-config" type="application/json">{"url_base_pathname": "/search/", "requests_pathname_prefix": "/search/", "ui": false, "props_check": false, "show_undo_redo": false, "suppress_callback_exceptions": true, "update_title": "Updating..."}</script>
            <script src="/search/_dash-component-suites/dash_renderer/polyfill@7.v1_8_2m1602816880.8.7.min.js"></script>
<script src="/search/_dash-component-suites/dash_renderer/react@16.v1_8_2m1602816880.13.0.min.js"></script>
<script src="/search/_dash-component-suites/dash_renderer/react-dom@16.v1_8_2m1602816880.13.0.min.js"></script>
<script src="/search/_dash-component-suites/dash_renderer/prop-types@15.v1_8_2m1602816880.7.2.min.js"></script>
<script src="/search/_dash-component-suites/dash_core_components/dash_core_components.v1_12_1m1602816883.min.js"></script>
<script src="/search/_dash-component-suites/dash_core_components/dash_core_components-shared.v1_12_1m1602816883.js"></script>
<script src="/search/_dash-component-suites/dash_html_components/dash_html_components.v1_1_1m1602816884.min.js"></script>
<script src="/search/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_10_7m1602816852.min.js"></script>
<script src="/search/assets/analytics.js?m=1564203257.8588707"></script>
<script src="/search/_dash-component-suites/dash_renderer/dash_renderer.v1_8_2m1602816880.min.js"></script>
            <script id="_dash-renderer" type="application/javascript">var renderer = new DashRenderer();</script>
        </footer>
    </body>
```

**Comment by sjtrny** [comment]
Here's a script I just wrote to use chromium and puppeteer to load the JS on the page. I'm using the [pyppeteer](https://github.com/pyppeteer/pyppeteer) package to do this from Python.

```
import asyncio
from pyppeteer import launch
import time

async def load_page_n_times(browser, n):
    page = await browser.newPage()
    for i in range(n):
        await page.goto('http://0.0.0.0:5000/search/')

async def main(n_conns, n_requests):

    browser = await launch()

    tasks = [
        load_page_n_times(browser, n_requests)
        for i in range(n_conns)
    ]

    start = time.time()
    await asyncio.gather(*tasks)
    print(f"Time elapsed: {time.time() - start}")

    await browser.close()


asyncio.run(main(64, 2))
```

**Comment by sjtrny** [comment]
I've played around with caching using instructions from here https://dash.plotly.com/performance

It hasn't made an impact on any of the timings listed above. So I think the bottleneck is actually the JS render performance and overhead from using pyppeteer/pupeteer/chromium.

**Comment by sjtrny** [comment]
Turns out that the bottleneck is actually from flask-caching which is quite inefficient. I swapped it out for functools.lru_cache and I can process 128 requests (4 connections with 32 requests each) in about 5 seconds with a single gunicorn worker.

```
        from functools import lru_cache as filter_cache
        @filter_cache(maxsize=50)
        def process_filter(**kwargs):
                # THIS FUNCTION HANDLES THE FILTERS

        @self.callback(
            Output("filter_results", "children"),
            [Input(i, "value") for i in component_ids],
        )
        @dash_kwarg([Input(i, "value") for i in component_ids])
        def filter_results(**kwargs):
            return process_filter(**{k:json.dumps(v) for k,v in kwargs.items()})

```

The main problem on the search page is the `filter_results` function which can take a few hundred milliseconds to complete.

Occasionally when load testing I noticed gunicorn fail because of too many open files on the system. I think this means we will also need to find a replacement for loading the .json files.

We might be able to solve performance and safety issues by putting a HTTP cache like varnish in front of gunicorn. We could even get it to invalidate the cache once a day after the updated has finished. In essence making the website static after the first hit of the day. However I've never used varnish before and I'm not sure we can control it like that programatically.

**Comment by sjtrny** [comment]
Looks like we can use the [python-vanish](https://github.com/justquick/python-varnish) package to "ban" urls from a varnish cache and you can ban the root path which should reset everything.

So that might form part of the solution.

Although there is still an unresolved edge case: receiving a huge number of requests immediately after we reset which would all be passed through to the web server. But this seems very unlikely at the moment.

**Comment by david-houseman** [comment]
Wow, this is great work. Yes, you are right, `wget` was not evaluating all the javascript so was not a good measurement. `pyppeteer` is much better.

I have run your chromium/pyppeteer script locally on my own machine and found similar results (note the variability in timing for N = 32, 64)
```
 N  Run1  Run2
 1: 1.446 1.464
 2: 1.097 1.678
 4: 1.145 1.159
 8: 1.612 1.803
16: 2.623 2.5830
32: 5.711 15.812
64: 8.404 28.070
```
I also tried stressing the production box as it is a smaller machine:
```
 N  Run1  Run2
 1: 1.995 2.028
 2: 1.978 1.988
 4: 2.042 2.140
 8: 2.261 2.777
16: 5.492 5.804
32: 12.503 13.0338
64: >30s (timeout) 28.034
```

**Comment by sjtrny** [comment]
I've created an `optimisations` branch to work on this issue. I've just made some minor changes so far but will have a crack at setting up a varnish server.

**Comment by sjtrny** [comment]
Turns out that varnish does not natively support caching of POST requests, which are happens to be request type used with the slow callbacks. We have to compile from source to add a plugin that enables this feature.

But it looks like NGINX has inbuilt support for this feature so I’ll try that next.

**Comment by sjtrny** [comment]
I've got caching working in `optimisations` using NGINX. I think it will be sufficient to handle our expected traffic levels.

I said earlier

> Although there is still an unresolved edge case: receiving a huge number of requests immediately after we reset which would all be passed through to the web server. But this seems very unlikely at the moment.

Fortunately NGINX has two options to stop this from happening:

- proxy_cache_lock (holds requests at NGINX until the first has finished, then returns the result to all requests)
- proxy_cache_use_stale (if the cache is being updated the old version will be served)

**Next steps: set up cache purging.**

**Comment by sjtrny** [comment]
The selective purge features are only available in nginx plus (paid service) or via a [third party module ](https://github.com/FRiCKLE/ngx_cache_purge), which needs to be compiled.

Fortunately we only need to purge the entire cache once a day, which can be achieved by deleting all the cache files on disk.

My solution so far:

1. Create docker volume to store the cache files
2. Give the nginx and updater service read/write access to the volume
3. The updater service deletes all files in the cache once it has completed

**Comment by sjtrny** [comment]
Caching is now live along with some minor performance improvements.
