### ISSUE TITLE
Scoring tooltips

### ISSUE THREAD

**Issue by sjtrny** [forecastlab/forecast_dash#90]
On the score table add a tooltip that shows information about each of the scores

https://dash.plotly.com/datatable/tooltips

**Comment by rjames6023** [comment]
@sjtrny did we want to include mathematical formulas in the tooltip descriptions or just words and leave the formulas for the  documentation pages?

**Comment by sjtrny** [comment]
> @sjtrny did we want to include mathematical formulas in the tooltip descriptions or just words and leave the formulas for the documentation pages?

Yep I think the tooltips should be just a written description. Formulas are best left to the documentation pages for those that care.
